Repository UMC-YouRun/YouRun_Android, pull requests merged in 2025-01, with the labels that each got.

#6 Feature/#4로그인 및 회원가입 UI 추가
  .idea/.name
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/view/activities/LoginActivity.kt
  app/src/main/java/com/example/yourun/view/activities/MainActivity.kt
  app/src/main/java/com/example/yourun/view/activities/SignUp1Activity.kt
  app/src/main/java/com/example/yourun/view/activities/SignUp2Activity.kt
  app/src/main/java/com/example/yourun/view/activities/SignUp3Activity.kt
  app/src/main/res/drawable/bg_agree.xml
  app/src/main/res/drawable/bg_checkbox_selected.xml
  app/src/main/res/drawable/bg_checkbox_unselected.xml
  app/src/main/res/drawable/bg_edittext_rounded_corner.xml
  app/src/main/res/drawable/bg_tag_checkbox_checked.xml
  app/src/main/res/drawable/bg_tag_checkbox_default.xml
  app/src/main/res/drawable/bg_tag_checkbox_selector.xml
  app/src/main/res/drawable/ic_back.xml
  app/src/main/res/drawable/ic_check_box.xml
  app/src/main/res/drawable/ic_visibilityoff.xml
  app/src/main/res/drawable/img_againcheck.xml
  app/src/main/res/drawable/img_kakao_btn.xml
  app/src/main/res/drawable/img_line.xml
  app/src/main/res/drawable/img_line2.xml
  app/src/main/res/drawable/img_login_bar.xml
  app/src/main/res/drawable/img_login_btn.xml
  app/src/main/res/drawable/img_logo.xml
  app/src/main/res/drawable/img_next_btn.xml
  app/src/main/res/drawable/img_signup_bar.xml
  app/src/main/res/drawable/img_success.xml
  app/src/main/res/drawable/img_text.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_signup1.xml
  app/src/main/res/layout/activity_signup2.xml
  app/src/main/res/layout/activity_signup3.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles:루나:sparkles:, :white_check_mark:FEATURE, :computer:UI

#8 Feature/#2 성향테스트
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/model/data/Question.kt
  app/src/main/java/com/example/yourun/model/data/ResultData.kt
  app/src/main/java/com/example/yourun/model/repository/QuestionRepository.kt
  app/src/main/java/com/example/yourun/model/repository/ResultRepository.kt
  app/src/main/java/com/example/yourun/model/viewmodel/NextButtonViewModel.kt
  app/src/main/java/com/example/yourun/utils/DimensionUtils.kt
  app/src/main/java/com/example/yourun/view/activities/QuestionActivity.kt
  app/src/main/java/com/example/yourun/view/activities/ResultActivity.kt
  app/src/main/java/com/example/yourun/view/adapters/QuestionPagerAdapter.kt
  app/src/main/res/drawable/bgd_circle.xml
  app/src/main/res/drawable/bgd_rounded_box.xml
  app/src/main/res/drawable/bgd_toolbar.xml
  app/src/main/res/drawable/bgd_yellow.xml
  app/src/main/res/drawable/btn_next.xml
  app/src/main/res/drawable/btn_question_background.xml
  app/src/main/res/drawable/ic_left.xml
  app/src/main/res/drawable/img_check.xml
  app/src/main/res/drawable/img_facemaker.png
  app/src/main/res/drawable/img_sprinter.png
  app/src/main/res/drawable/img_trailrunner.png
  app/src/main/res/layout/activity_question.xml
  app/src/main/res/layout/activity_result.xml
  app/src/main/res/layout/item_question.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/themes.xml
  dependencies.txt
  gradle/libs.versions.toml
  gradlew
Labels: :sparkles:졍:sparkles:, :white_check_mark:FEATURE, :computer:UI

#12 feature/#9 마이런 페이지 UI 구현
  .idea/deploymentTargetSelector.xml
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/view/activities/LoginActivity.kt
  app/src/main/java/com/example/yourun/view/activities/MyRun1Activity.kt
  app/src/main/java/com/example/yourun/view/activities/MyRun2Activity.kt
  app/src/main/java/com/example/yourun/view/activities/SignUp1Activity.kt
  app/src/main/java/com/example/yourun/view/activities/SignUp2Activity.kt
  app/src/main/java/com/example/yourun/view/activities/SignUp3Activity.kt
  app/src/main/res/drawable/bg_big_circle.xml
  app/src/main/res/drawable/bg_checkbox.xml
  app/src/main/res/drawable/bg_gray_box.xml
  app/src/main/res/drawable/bg_small_circle.xml
  app/src/main/res/drawable/bg_tag_checkbox_selector.xml
  app/src/main/res/drawable/ic_calendar.xml
  app/src/main/res/drawable/ic_check_box.xml
  app/src/main/res/drawable/ic_check_box_selected.xml
  app/src/main/res/drawable/ic_myrun.xml
  app/src/main/res/drawable/ic_visibilityon.xml
  app/src/main/res/drawable/img_btn_signup.xml
  app/src/main/res/drawable/img_change_myrun_btn.xml
  app/src/main/res/drawable/img_crew_reward1.xml
  app/src/main/res/drawable/img_crew_reward2.xml
  app/src/main/res/drawable/img_face01.png
  app/src/main/res/drawable/img_kakao_btn.xml
  app/src/main/res/drawable/img_kakao_login1.png
  app/src/main/res/drawable/img_mask_group.xml
  app/src/main/res/drawable/img_mvp.xml
  app/src/main/res/drawable/img_myrun_ranking.xml
  app/src/main/res/drawable/img_profile1.xml
  app/src/main/res/drawable/img_profile_bg.xml
  app/src/main/res/drawable/img_promaker.xml
  app/src/main/res/drawable/rounded_bottom_background2.xml
  app/src/main/res/layout/activity_login.xml
  app/src/main/res/layout/activity_myrun1.xml
  app/src/main/res/layout/activity_myrun2.xml
  app/src/main/res/layout/activity_question.xml
  app/src/main/res/layout/activity_signup1.xml
  app/src/main/res/layout/activity_signup2.xml
  app/src/main/res/layout/activity_signup3.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles:루나:sparkles:, :white_check_mark:FEATURE, :computer:UI

#16 Feature/#10 홈 화면 UI 구현
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/view/activities/MainActivity.kt
  app/src/main/java/com/example/yourun/view/custom/CustomHomeChallenge.kt
  app/src/main/java/com/example/yourun/view/fragments/AppExpFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/AppExpFragment2.kt
  app/src/main/java/com/example/yourun/view/fragments/AppExpFragment3.kt
  app/src/main/java/com/example/yourun/view/fragments/AppExpFragment4.kt
  app/src/main/java/com/example/yourun/view/fragments/AppExpFragment5.kt
  app/src/main/java/com/example/yourun/view/fragments/ChallengeFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/HomeFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/MateFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/MyRunFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/RunningFragment.kt
  app/src/main/res/color/selector_icon_color.xml
  app/src/main/res/drawable/bgd_home_challenge.xml
  app/src/main/res/drawable/bgd_home_challenge_char.xml
  app/src/main/res/drawable/bgd_home_challenge_day.xml
  app/src/main/res/drawable/ic_add_challenge.xml
  app/src/main/res/drawable/ic_challenge.xml
  app/src/main/res/drawable/ic_crew_badge.xml
  app/src/main/res/drawable/ic_heart_selected.xml
  app/src/main/res/drawable/ic_heart_unselected.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_mate.xml
  app/src/main/res/drawable/ic_menu_myrun.xml
  app/src/main/res/drawable/ic_progressing_matching.xml
  app/src/main/res/drawable/ic_redirect.xml
  app/src/main/res/drawable/ic_solo_badge.xml
  app/src/main/res/drawable/ic_waiting_matching.xml
  app/src/main/res/drawable/img_character_face.xml
  app/src/main/res/drawable/img_crew_btn_selected.xml
  app/src/main/res/drawable/img_crew_btn_unselected.xml
  app/src/main/res/drawable/img_fire.png
  app/src/main/res/drawable/img_home_background.xml
  app/src/main/res/drawable/img_home_banner.png
  app/src/main/res/drawable/img_home_bgd_gradient.xml
  app/src/main/res/drawable/img_home_character.xml
  app/src/main/res/drawable/img_running.png
  app/src/main/res/drawable/img_solo_btn_selected.xml
  app/src/main/res/drawable/img_solo_btn_unselected.xml
  app/src/main/res/drawable/img_user_profile.xml
  app/src/main/res/drawable/img_women_running.png
  app/src/main/res/drawable/rounded_corners_day.xml
  app/src/main/res/drawable/rounded_top_corners.xml
  app/src/main/res/font/roboto.xml
  app/src/main/res/font/roboto_bolditalic.ttf
  app/src/main/res/font/roboto_medium.ttf
  app/src/main/res/font/roboto_semibold.ttf
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/bottom_navigation.xml
  app/src/main/res/layout/custom_home_challenge.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_similar_mate.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: :sparkles:이케:sparkles:, :white_check_mark:FEATURE, :computer:UI

#18 Feature/#12 캘린더 화면
  .idea/.name
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/view/activities/CalendarActivity.kt
  app/src/main/res/drawable/bgd_calendar.png
  app/src/main/res/drawable/box_distance.xml
  app/src/main/res/drawable/box_pace.xml
  app/src/main/res/drawable/box_time.xml
  app/src/main/res/drawable/ic_chat.png
  app/src/main/res/drawable/ic_distance.png
  app/src/main/res/drawable/ic_drag_bar.xml
  app/src/main/res/drawable/ic_pace.png
  app/src/main/res/drawable/ic_selected.xml
  app/src/main/res/drawable/ic_time.png
  app/src/main/res/drawable/img_calendar_left.png
  app/src/main/res/drawable/img_calendar_right.png
  app/src/main/res/layout/activity_calendar.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  gradle.properties
Labels: :sparkles:졍:sparkles:, :computer:UI

#20 feature/#19챌린지 생성 UI 구현
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/view/activities/CreateChallengeActivity.kt
  app/src/main/java/com/example/yourun/view/activities/CreateCrew1Activity.kt
  app/src/main/java/com/example/yourun/view/activities/CreateCrew2Activity.kt
  app/src/main/java/com/example/yourun/view/activities/CreateSolo1Activity.kt
  app/src/main/java/com/example/yourun/view/activities/CreateSolo2Activity.kt
  app/src/main/res/drawable/current_date_purple.xml
  app/src/main/res/drawable/ic_myrun.xml
  app/src/main/res/drawable/img_facemaker_challenge.png
  app/src/main/res/drawable/img_plus_logo.xml
  app/src/main/res/drawable/range_gradient_yellow.xml
  app/src/main/res/drawable/rounded_button.xml
  app/src/main/res/drawable/selected_date_orange.xml
  app/src/main/res/layout/activity_create_challenge.xml
  app/src/main/res/layout/activity_create_crew1.xml
  app/src/main/res/layout/activity_create_crew2.xml
  app/src/main/res/layout/activity_create_solo1.xml
  app/src/main/res/layout/activity_create_solo2.xml
  app/src/main/res/layout/activity_myrun1.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  gradle/libs.versions.toml
Labels: :sparkles:루나:sparkles:, :white_check_mark:FEATURE, :computer:UI

#23 Feature/#11 온보딩 화면 구현
  .idea/.gitignore
  .idea/deploymentTargetSelector.xml
  .idea/vcs.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/assets/onboarding_animation.json
  app/src/main/java/com/example/yourun/view/activities/MainActivity.kt
  app/src/main/java/com/example/yourun/view/activities/OnboardingActivity.kt
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles:아리:sparkles:, :white_check_mark:FEATURE, :computer:UI

#22 Feature/#17 러닝 진행 화면 UI 구현
  .idea/.name
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/view/activities/RunningActivity.kt
  app/src/main/java/com/example/yourun/view/activities/RunningResultActivity.kt
  app/src/main/java/com/example/yourun/view/fragments/AppExpFragment2.kt
  app/src/main/java/com/example/yourun/view/fragments/AppExpFragment3.kt
  app/src/main/java/com/example/yourun/view/fragments/AppExpFragment4.kt
  app/src/main/java/com/example/yourun/view/fragments/AppExpFragment5.kt
  app/src/main/java/com/example/yourun/view/fragments/RunningFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/RunningMateSelectFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/RunningTimeFragment.kt
  app/src/main/res/drawable/bgd_mate_profile.xml
  app/src/main/res/drawable/bgd_mate_selected.xml
  app/src/main/res/drawable/bgd_mate_unselected.xml
  app/src/main/res/drawable/bgd_rotating_circle.xml
  app/src/main/res/drawable/bgd_running_result_frame.xml
  app/src/main/res/drawable/custom_rounded_button.xml
  app/src/main/res/drawable/ic_15_minute.xml
  app/src/main/res/drawable/ic_30_minute.xml
  app/src/main/res/drawable/ic_45_minute.xml
  app/src/main/res/drawable/ic_60_minute.xml
  app/src/main/res/drawable/ic_arrow_right.xml
  app/src/main/res/drawable/ic_mate_select.xml
  app/src/main/res/drawable/ic_ok.xml
  app/src/main/res/drawable/ic_pause.xml
  app/src/main/res/drawable/ic_play.xml
  app/src/main/res/drawable/ic_play_pause_selector.xml
  app/src/main/res/drawable/ic_running_start.xml
  app/src/main/res/drawable/ic_running_time.xml
  app/src/main/res/drawable/ic_select.xml
  app/src/main/res/drawable/img_clock.xml
  app/src/main/res/drawable/img_clock_white.xml
  app/src/main/res/drawable/img_distance.xml
  app/src/main/res/drawable/img_fire_white.xml
  app/src/main/res/drawable/img_question_mark.xml
  app/src/main/res/drawable/img_running_character.xml
  app/src/main/res/drawable/img_speech_bubble.xml
  app/src/main/res/drawable/rounded_bottom_corners.xml
  app/src/main/res/drawable/rounded_corners_distance.xml
  app/src/main/res/drawable/rounded_corners_map.xml
  app/src/main/res/drawable/rounded_top_corners_map.xml
  app/src/main/res/layout/activity_running.xml
  app/src/main/res/layout/activity_running_result.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_running.xml
  app/src/main/res/layout/fragment_running_mate_select.xml
  app/src/main/res/layout/fragment_running_time.xml
  app/src/main/res/layout/item_similar_mate.xml
  app/src/main/res/layout/top_bar_with_back_button.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles:이케:sparkles:, :white_check_mark:FEATURE, :computer:UI

#26 Feature/#25챌린지 결과
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/view/activities/ResultContributionActivity.kt
  app/src/main/java/com/example/yourun/view/activities/ResultCrewActivity.kt
  app/src/main/java/com/example/yourun/view/activities/ResultSoloActivity.kt
  app/src/main/java/com/example/yourun/view/fragments/ChallengeFragment.kt
  app/src/main/res/drawable/bg_tag.xml
  app/src/main/res/drawable/bgd_crew_bar.xml
  app/src/main/res/drawable/bgd_crew_purple.xml
  app/src/main/res/drawable/bgd_crew_yellow.xml
  app/src/main/res/drawable/bgd_yellow_bubble.xml
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/ic_arrow_up.xml
  app/src/main/res/drawable/ic_crew.png
  app/src/main/res/drawable/ic_stamp_default.xml
  app/src/main/res/drawable/ic_stamp_fail.xml
  app/src/main/res/drawable/ic_stamp_success.xml
  app/src/main/res/drawable/img_crew_facemaker.png
  app/src/main/res/drawable/img_crew_fail_01.png
  app/src/main/res/drawable/img_crew_fail_02.png
  app/src/main/res/drawable/img_crew_fail_03.png
  app/src/main/res/drawable/img_crew_success_01.png
  app/src/main/res/drawable/img_crew_success_02.png
  app/src/main/res/drawable/img_crew_success_03.png
  app/src/main/res/drawable/img_crew_trailrunner.png
  app/src/main/res/drawable/img_running_failed.png
  app/src/main/res/drawable/img_running_success.png
  app/src/main/res/drawable/progress_bar_custom.xml
  app/src/main/res/drawable/rounded_confirm_button.xml
  app/src/main/res/layout/activity_result_crew.xml
  app/src/main/res/layout/activity_result_crew_contribution.xml
  app/src/main/res/layout/activity_result_solo.xml
  app/src/main/res/layout/activity_running_challenge.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles:졍:sparkles:, :computer:UI
