Repository UMC-YouRun/YouRun_Android, pull requests merged in 2025-02, with the labels that each got.

#35 feature/#34로그인및회원가입api연결
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/model/data/EmailduplicateResponse.kt
  app/src/main/java/com/example/yourun/model/data/LoginRequest.kt
  app/src/main/java/com/example/yourun/model/data/SignupRequest.kt
  app/src/main/java/com/example/yourun/model/network/ApiClient.kt
  app/src/main/java/com/example/yourun/model/network/ApiService.kt
  app/src/main/java/com/example/yourun/view/activities/LoginActivity.kt
  app/src/main/java/com/example/yourun/view/activities/SignUp1Activity.kt
  app/src/main/res/drawable/btn_check.xml
  app/src/main/res/drawable/btn_choice.xml
  app/src/main/res/drawable/btn_create.xml
  app/src/main/res/drawable/btn_test_again.xml
  app/src/main/res/layout/activity_create_challenge.xml
  app/src/main/res/layout/activity_create_crew1.xml
  app/src/main/res/layout/activity_create_crew2.xml
  app/src/main/res/layout/activity_create_solo1.xml
  app/src/main/res/layout/activity_create_solo2.xml
  app/src/main/res/layout/activity_myrun1.xml
  app/src/main/res/layout/activity_myrun2.xml
  app/src/main/res/layout/activity_onboarding.xml
  app/src/main/res/layout/activity_signup1.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/xml/network_security_config.xml
Labels: :sparkles:루나:sparkles:, :white_check_mark:FEATURE

#40 feature/#39_ui수정및화면연결
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/model/data/SignupRequest.kt
  app/src/main/java/com/example/yourun/model/network/ApiClient.kt
  app/src/main/java/com/example/yourun/model/network/ApiService.kt
  app/src/main/java/com/example/yourun/view/activities/CreateChallengeActivity.kt
  app/src/main/java/com/example/yourun/view/activities/CreateCrew1Activity.kt
  app/src/main/java/com/example/yourun/view/activities/CreateCrew2Activity.kt
  app/src/main/java/com/example/yourun/view/activities/CreateSolo1Activity.kt
  app/src/main/java/com/example/yourun/view/activities/CreateSolo2Activity.kt
  app/src/main/java/com/example/yourun/view/activities/LoginActivity.kt
  app/src/main/res/layout/activity_create_crew1.xml
  app/src/main/res/layout/activity_onboarding.xml
  gradle/libs.versions.toml
Labels: :sparkles:루나:sparkles:, :computer:UI, :exclamation:REFRACTOR

#41 fix/#15 챌린지목록 화면 파일 복원
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/model/data/ChallengeItem.kt
  app/src/main/java/com/example/yourun/view/activities/ChallengeDetailPersonalActivity.kt
  app/src/main/java/com/example/yourun/view/activities/ChallengeDetailTeamActivity.kt
  app/src/main/java/com/example/yourun/view/activities/ChallengeListActivity.kt
  app/src/main/java/com/example/yourun/view/adapters/ChallengeAdapter.kt
  app/src/main/res/drawable/bg_headcount.xml
  app/src/main/res/drawable/bg_user_profile.xml
  app/src/main/res/drawable/btn_crew.xml
  app/src/main/res/drawable/btn_join.xml
  app/src/main/res/drawable/btn_personal.xml
  app/src/main/res/drawable/img_badge_c.xml
  app/src/main/res/drawable/img_badge_s.xml
  app/src/main/res/drawable/img_bar_horizontal.xml
  app/src/main/res/drawable/img_crew_badge_count.xml
  app/src/main/res/drawable/img_grey_box.xml
  app/src/main/res/drawable/img_mini2_pacemaker.xml
  app/src/main/res/drawable/img_mini2_sprinter.xml
  app/src/main/res/drawable/img_mini2_trailrunner.xml
  app/src/main/res/drawable/img_mini_pacemaker.xml
  app/src/main/res/drawable/img_mini_sprinter.xml
  app/src/main/res/drawable/img_mini_trailrunner.xml
  app/src/main/res/drawable/img_rewards.xml
  app/src/main/res/drawable/img_user.xml
  app/src/main/res/layout/activity_challenge_detail_personal.xml
  app/src/main/res/layout/activity_challenge_detail_team.xml
  app/src/main/res/layout/activity_challenge_list.xml
  app/src/main/res/layout/item_challenge.xml
  app/src/main/res/layout/item_footer.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/strings.xml
Labels: :sparkles:아리:sparkles:, :hammer:FIX

#43 Feature/#37 홈 화면 챌린지 조회 구현
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/model/data/HomeChallengeResponse.kt
  app/src/main/java/com/example/yourun/model/data/MemberTendencyInfo.kt
  app/src/main/java/com/example/yourun/model/data/SignupRequest.kt
  app/src/main/java/com/example/yourun/model/data/UserCrewChallengeInfo.kt
  app/src/main/java/com/example/yourun/model/data/UserSoloChallengeInfo.kt
  app/src/main/java/com/example/yourun/model/network/ApiClient.kt
  app/src/main/java/com/example/yourun/model/network/HomeApiService.kt
  app/src/main/java/com/example/yourun/model/repository/HomeChallengeRepository.kt
  app/src/main/java/com/example/yourun/view/activities/LoginActivity.kt
  app/src/main/java/com/example/yourun/view/activities/SignUp1Activity.kt
  app/src/main/java/com/example/yourun/view/custom/CustomHomeChallenge.kt
  app/src/main/java/com/example/yourun/view/fragments/HomeFragment.kt
  app/src/main/java/com/example/yourun/viewmodel/HomeViewModel.kt
  app/src/main/java/com/example/yourun/viewmodel/HomeViewModelFactory.kt
  app/src/main/res/drawable/img_circle_profile_facemaker.xml
  app/src/main/res/drawable/img_circle_profile_sprinter.xml
  app/src/main/res/drawable/img_circle_profile_trailrunner.xml
  app/src/main/res/layout/custom_home_challenge.xml
  app/src/main/res/layout/fragment_home.xml
Labels: :sparkles:이케:sparkles:, :white_check_mark:FEATURE

#45 Feature/#44 러닝 결과 정보 생성 요청 api 구현
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/model/data/RunningResultRequest.kt
  app/src/main/java/com/example/yourun/model/data/RunningResultResponse.kt
  app/src/main/java/com/example/yourun/model/network/ApiClient.kt
  app/src/main/java/com/example/yourun/model/network/RunningApiService.kt
  app/src/main/java/com/example/yourun/view/activities/ResultCrewActivity.kt
  app/src/main/java/com/example/yourun/view/activities/ResultSoloActivity.kt
  app/src/main/java/com/example/yourun/view/activities/RunningActivity.kt
  app/src/main/java/com/example/yourun/view/activities/RunningResultActivity.kt
  app/src/main/java/com/example/yourun/view/fragments/RunningFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/RunningTimeFragment.kt
  app/src/main/java/com/example/yourun/viewmodel/RunningViewModel.kt
  app/src/main/java/com/example/yourun/viewmodel/RunningViewModelFactory.kt
  app/src/main/res/drawable/bgd_time_button.xml
  app/src/main/res/drawable/ic_heart_selector.xml
  app/src/main/res/drawable/rounded_time_button_selected.xml
  app/src/main/res/layout/activity_running.xml
  app/src/main/res/layout/activity_running_result.xml
  app/src/main/res/layout/fragment_running_time.xml
  app/src/main/res/layout/item_similar_mate.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/strings.xml
Labels: :sparkles:이케:sparkles:, :white_check_mark:FEATURE

#49 feature/#46 로그인 기능 api연결 및 토큰 저장
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/model/data/LoginRequest.kt
  app/src/main/java/com/example/yourun/model/data/LoginResponse.kt
  app/src/main/java/com/example/yourun/model/network/ApiClient.kt
  app/src/main/java/com/example/yourun/model/network/ApiService.kt
  app/src/main/java/com/example/yourun/model/network/AuthInterceptor.kt
  app/src/main/java/com/example/yourun/model/network/RetrofitClient.kt
  app/src/main/java/com/example/yourun/model/repository/LoginRepository.kt
  app/src/main/java/com/example/yourun/utils/TokenManager.kt
  app/src/main/java/com/example/yourun/view/activities/AppExpActivity.kt
  app/src/main/java/com/example/yourun/view/activities/LoginActivity.kt
  app/src/main/java/com/example/yourun/view/activities/MyRun1Activity.kt
  app/src/main/java/com/example/yourun/view/activities/MyRunActivity.kt
  app/src/main/java/com/example/yourun/view/activities/SignUp1Activity.kt
  app/src/main/java/com/example/yourun/view/activities/SignUp3Activity.kt
  app/src/main/java/com/example/yourun/view/fragments/AppExpFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/MyRunFragment.kt
  app/src/main/java/com/example/yourun/viewmodel/LoginViewModelFactory.kt
  app/src/main/java/com/example/yourun/viewmodel/LoginViewModle.kt
  app/src/main/res/layout/activity_myrun.xml
  app/src/main/res/layout/activity_myrun1.xml
  app/src/main/res/layout/fragment_myrun.xml
  gradle/libs.versions.toml
Labels: :sparkles:루나:sparkles:, :hammer:FIX, :exclamation:REFRACTOR

#55 Feature/#50 홈 화면 api 연결
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/MyApplication.kt
  app/src/main/java/com/example/yourun/model/data/ApiResponseBoolean.kt
  app/src/main/java/com/example/yourun/model/data/HomeChallengeResponse.kt
  app/src/main/java/com/example/yourun/model/data/LoginResponse.kt
  app/src/main/java/com/example/yourun/model/data/RecommendMateResponse.kt
  app/src/main/java/com/example/yourun/model/data/UserCrewChallengeInfo.kt
  app/src/main/java/com/example/yourun/model/network/ApiClient.kt
  app/src/main/java/com/example/yourun/model/network/ApiService.kt
  app/src/main/java/com/example/yourun/model/network/AuthInterceptor.kt
  app/src/main/java/com/example/yourun/model/network/HomeApiService.kt
  app/src/main/java/com/example/yourun/model/network/RetrofitClient.kt
  app/src/main/java/com/example/yourun/model/repository/HomeChallengeRepository.kt
  app/src/main/java/com/example/yourun/model/repository/HomeRepository.kt
  app/src/main/java/com/example/yourun/model/repository/LoginRepository.kt
  app/src/main/java/com/example/yourun/utils/TokenManager.kt
  app/src/main/java/com/example/yourun/view/activities/AppExpActivity.kt
  app/src/main/java/com/example/yourun/view/activities/LoginActivity.kt
  app/src/main/java/com/example/yourun/view/activities/MainActivity.kt
  app/src/main/java/com/example/yourun/view/custom/CustomHomeChallenge.kt
  app/src/main/java/com/example/yourun/view/custom/CustomMateView.kt
  app/src/main/java/com/example/yourun/view/fragments/AppExpFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/HomeFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/SignUpFragment1.kt
  app/src/main/java/com/example/yourun/viewmodel/HomeViewModel.kt
  app/src/main/java/com/example/yourun/viewmodel/HomeViewModelFactory.kt
  app/src/main/java/com/example/yourun/viewmodel/LoginViewModle.kt
  app/src/main/java/com/example/yourun/viewmodel/RunningViewModel.kt
  app/src/main/res/drawable/ic_complete.xml
  app/src/main/res/drawable/img_characters.png
  app/src/main/res/drawable/img_characters.xml
  app/src/main/res/drawable/img_characters2.png
  app/src/main/res/drawable/img_characters2.xml
  app/src/main/res/drawable/img_characters3.png
  app/src/main/res/drawable/img_characters3.xml
  app/src/main/res/layout/custom_home_challenge.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_similar_mate.xml
Labels: :sparkles:이케:sparkles:, :exclamation:REFRACTOR

#56 Feature/#54_캘린더api연결
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/model/data/RunningStatsResponse.kt
  app/src/main/java/com/example/yourun/model/data/SignupRequest.kt
  app/src/main/java/com/example/yourun/model/network/ApiClientNoAuth.kt
  app/src/main/java/com/example/yourun/model/network/ApiService.kt
  app/src/main/java/com/example/yourun/model/repository/ResultRepository.kt
  app/src/main/java/com/example/yourun/view/activities/CalendarActivity.kt
  app/src/main/java/com/example/yourun/view/activities/LoginActivity.kt
  app/src/main/java/com/example/yourun/view/activities/QuestionActivity.kt
  app/src/main/java/com/example/yourun/view/activities/ResultActivity.kt
  app/src/main/java/com/example/yourun/view/fragments/ResultFragment.kt
  app/src/main/java/com/example/yourun/viewmodel/SignupViewModel.kt
  app/src/main/res/layout/activity_calendar.xml
Labels: :sparkles:졍:sparkles:, :hammer:FIX, :white_check_mark:FEATURE

#58 feature/#55_개인러닝챌린지
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/model/data/ChallengeDataResponse.kt
  app/src/main/java/com/example/yourun/model/data/ChallengeResultResponse.kt
  app/src/main/java/com/example/yourun/model/network/ApiService.kt
  app/src/main/java/com/example/yourun/view/activities/CalendarActivity.kt
  app/src/main/java/com/example/yourun/view/activities/MainActivity.kt
  app/src/main/java/com/example/yourun/view/activities/ResultSoloActivity.kt
  app/src/main/java/com/example/yourun/view/fragments/ChallengeFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/SignUpFragment1.kt
  app/src/main/java/com/example/yourun/viewmodel/ChallengeResultViewModel.kt
  app/src/main/res/layout/fragment_home.xml
Labels: :sparkles:졍:sparkles:, :white_check_mark:FEATURE

#59 feature/#53닉네임 중복 확인
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/model/data/NicknameduplicateResponse.kt
  app/src/main/java/com/example/yourun/model/data/UserInfo.kt
  app/src/main/java/com/example/yourun/model/network/ApiClient.kt
  app/src/main/java/com/example/yourun/model/network/ApiService.kt
  app/src/main/java/com/example/yourun/model/repository/MyRunRepository.kt
  app/src/main/java/com/example/yourun/view/activities/CreateCrew1Activity.kt
  app/src/main/java/com/example/yourun/view/fragments/MyRunFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/SignUpFragment3.kt
  app/src/main/java/com/example/yourun/viewmodel/MyRunViewModel.kt
  app/src/main/java/com/example/yourun/viewmodel/MyRunViewModelFactory.kt
  app/src/main/res/layout/fragment_myrun.xml
  app/src/main/res/layout/fragment_signup3.xml
Labels: :sparkles:루나:sparkles:, :exclamation:REFRACTOR

#69 Refactor/#68 러닝 기능 수정
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/yourun/model/data/request/CreateCrewChallengeRequest.kt
  app/src/main/java/com/example/yourun/model/data/request/CreateSoloChallengeRequest.kt
  app/src/main/java/com/example/yourun/model/data/request/UpdateUserRequest.kt
  app/src/main/java/com/example/yourun/model/data/response/CreateCrewChallengeResponse.kt
  app/src/main/java/com/example/yourun/model/data/response/CreateSoloChallengeResponse.kt
  app/src/main/java/com/example/yourun/model/data/response/NicknameduplicateResponse.kt
  app/src/main/java/com/example/yourun/model/data/response/UpdateUserResponse.kt
  app/src/main/java/com/example/yourun/model/data/response/UserInfo.kt
  app/src/main/java/com/example/yourun/model/network/ApiService.kt
  app/src/main/java/com/example/yourun/model/repository/HomeRepository.kt
  app/src/main/java/com/example/yourun/model/repository/MyRunRepository.kt
  app/src/main/java/com/example/yourun/model/repository/RunningRepository.kt
  app/src/main/java/com/example/yourun/view/activities/MyRun2Activity.kt
  app/src/main/java/com/example/yourun/view/activities/RunningActivity.kt
  app/src/main/java/com/example/yourun/view/activities/RunningResultActivity.kt
  app/src/main/java/com/example/yourun/view/fragments/CreateCrew1Fragment.kt
  app/src/main/java/com/example/yourun/view/fragments/CreateSolo1Fragment.kt
  app/src/main/java/com/example/yourun/view/fragments/HomeFragment.kt
  app/src/main/java/com/example/yourun/viewmodel/HomeViewModel.kt
  app/src/main/java/com/example/yourun/viewmodel/MyRunViewModel.kt
  app/src/main/java/com/example/yourun/viewmodel/RunningViewModel.kt
  app/src/main/res/drawable/bgd_small_speech_bubble.xml
  app/src/main/res/drawable/custom_progress_bar.xml
  app/src/main/res/layout/activity_running.xml
  app/src/main/res/layout/activity_running_result.xml
  app/src/main/res/values/colors.xml
Labels: :sparkles:이케:sparkles:, :exclamation:REFRACTOR

#76 feature/#72디테일수정
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/model/data/MateResponse.kt
  app/src/main/java/com/example/yourun/model/repository/MateRepository.kt
  app/src/main/java/com/example/yourun/view/activities/LoginActivity.kt
  app/src/main/java/com/example/yourun/view/activities/MainActivity.kt
  app/src/main/java/com/example/yourun/view/activities/MyRun2Activity.kt
  app/src/main/java/com/example/yourun/view/activities/RunningActivity.kt
  app/src/main/java/com/example/yourun/view/activities/RunningResultActivity.kt
  app/src/main/java/com/example/yourun/view/fragments/AppExpFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/AppExpFragment6.kt
  app/src/main/java/com/example/yourun/view/fragments/CreateCrew2Fragment.kt
  app/src/main/java/com/example/yourun/view/fragments/CreateSolo2Fragment.kt
  app/src/main/java/com/example/yourun/view/fragments/MateFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/ResultFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/RunningFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/RunningMateSelectFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/RunningTimeFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/SignUpFragment1.kt
  app/src/main/java/com/example/yourun/view/fragments/SignUpFragment3.kt
  app/src/main/java/com/example/yourun/viewmodel/RunningViewModelFactory.kt
  app/src/main/res/drawable/img_again_check_color.xml
  app/src/main/res/drawable/img_solo_progress_fail.png
  app/src/main/res/drawable/img_solo_progress_success.png
  app/src/main/res/drawable/img_solo_progress_vector.png
  app/src/main/res/drawable/img_stamp_date1.xml
  app/src/main/res/drawable/img_stamp_date2.xml
  app/src/main/res/drawable/img_stamp_date3.xml
  app/src/main/res/drawable/img_stamp_date4.xml
  app/src/main/res/drawable/img_stamp_date5.xml
  app/src/main/res/drawable/img_stamp_yet.png
  app/src/main/res/layout/activity_solo_progress.xml
  app/src/main/res/layout/fragment_create_crew1.xml
  app/src/main/res/layout/fragment_create_solo1.xml
  app/src/main/res/values/colors.xml
Labels: :sparkles:루나:sparkles:, :hammer:FIX, :computer:UI, :exclamation:REFRACTOR

#78 Fix/#77 러닝 오류 수정
  .idea/deploymentTargetSelector.xml
  app/src/main/java/com/example/yourun/model/network/ApiClient.kt
  app/src/main/java/com/example/yourun/model/network/RunningApiService.kt
  app/src/main/java/com/example/yourun/model/repository/MateRepository.kt
  app/src/main/java/com/example/yourun/view/activities/RunningResultActivity.kt
  app/src/main/java/com/example/yourun/view/fragments/HomeFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/MateFragment.kt
  app/src/main/java/com/example/yourun/viewmodel/RunningViewModel.kt
Labels: :bug:bug, :sparkles:이케:sparkles:, :hammer:FIX

#84 feature/#80_챌린지 화면
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/MyApplication.kt
  app/src/main/java/com/example/yourun/model/data/response/ChallengeMatchingResponse.kt
  app/src/main/java/com/example/yourun/model/data/response/CrewChallengeProgressResponse.kt
  app/src/main/java/com/example/yourun/model/data/response/SoloChallengeProgressResponse.kt
  app/src/main/java/com/example/yourun/model/network/ApiClient.kt
  app/src/main/java/com/example/yourun/model/network/ApiService.kt
  app/src/main/java/com/example/yourun/model/network/ChallengeApiService.kt
  app/src/main/java/com/example/yourun/model/repository/HomeRepository.kt
  app/src/main/java/com/example/yourun/model/repository/RunningRepository.kt
  app/src/main/java/com/example/yourun/utils/ChallengeCheckManager.kt
  app/src/main/java/com/example/yourun/view/activities/CrewProgressActivity.kt
  app/src/main/java/com/example/yourun/view/activities/LoginActivity.kt
  app/src/main/java/com/example/yourun/view/activities/ResultContributionActivity.kt
  app/src/main/java/com/example/yourun/view/activities/ResultCrewActivity.kt
  app/src/main/java/com/example/yourun/view/activities/ResultSoloActivity.kt
  app/src/main/java/com/example/yourun/view/activities/SoloProgressActivity.kt
  app/src/main/java/com/example/yourun/view/fragments/HomeFragment.kt
  app/src/main/java/com/example/yourun/viewmodel/CrewChallengeResultViewModel.kt
  app/src/main/java/com/example/yourun/viewmodel/CrewProgressViewModel.kt
  app/src/main/java/com/example/yourun/viewmodel/HomeViewModel.kt
  app/src/main/java/com/example/yourun/viewmodel/RunningViewModel.kt
  app/src/main/java/com/example/yourun/viewmodel/SoloProgressViewModel.kt
  app/src/main/res/drawable/bg_box_crew.xml
  app/src/main/res/drawable/bg_solo_mate.xml
  app/src/main/res/drawable/ic_challenge_crew_bubble.xml
  app/src/main/res/drawable/ic_crew_stamp.png
  app/src/main/res/drawable/img_challenge_facemaker.png
  app/src/main/res/drawable/img_crew_box.xml
  app/src/main/res/drawable/img_facemaker_1.png
  app/src/main/res/drawable/img_facemaker_3.png
  app/src/main/res/drawable/img_fcemaker_2.png
  app/src/main/res/drawable/img_grayboxline.xml
  app/src/main/res/drawable/img_solo_progress_fail.png
  app/src/main/res/drawable/img_solo_progress_success.png
  app/src/main/res/drawable/img_sprinter_1.png
  app/src/main/res/drawable/img_sprinter_2.png
  app/src/main/res/drawable/img_sprinter_3.png
  app/src/main/res/drawable/img_stamp_default.png
  app/src/main/res/drawable/img_stamp_fail.png
  app/src/main/res/drawable/img_stamp_success.png
  app/src/main/res/drawable/img_trailrunner_1.png
  app/src/main/res/drawable/img_trailrunner_2.png
  app/src/main/res/drawable/img_trailrunner_3.png
  app/src/main/res/layout/activity_challenge_crew_progress.xml
  app/src/main/res/layout/activity_result_crew.xml
  app/src/main/res/layout/activity_result_crew_contribution.xml
  app/src/main/res/layout/activity_result_solo.xml
  app/src/main/res/layout/activity_solo_progress.xml
  app/src/main/res/values/strings.xml
Labels: :sparkles:졍:sparkles:, :white_check_mark:FEATURE

#83 Feature/#79 카카오 로그인
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/model/data/response/RunningResultResponse.kt
  app/src/main/java/com/example/yourun/model/network/ApiService.kt
  app/src/main/java/com/example/yourun/model/repository/LoginRepository.kt
  app/src/main/java/com/example/yourun/view/activities/LoginActivity.kt
  app/src/main/java/com/example/yourun/view/activities/MainActivity.kt
  app/src/main/java/com/example/yourun/view/activities/RunningActivity.kt
  app/src/main/java/com/example/yourun/view/activities/RunningResultActivity.kt
  app/src/main/java/com/example/yourun/view/custom/CustomHomeChallenge.kt
  app/src/main/java/com/example/yourun/view/fragments/AppExpFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/HomeFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/RunningFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/RunningMateSelectFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/RunningTimeFragment.kt
  app/src/main/java/com/example/yourun/viewmodel/LoginViewModel.kt
  app/src/main/java/com/example/yourun/viewmodel/RunningViewModelFactory.kt
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/item_similar_mate.xml
Labels: :sparkles:이케:sparkles:, :white_check_mark:FEATURE, :exclamation:REFRACTOR

#89 feature/#88디테일 수정
  app/src/main/java/com/example/yourun/view/activities/RunningActivity.kt
  app/src/main/java/com/example/yourun/view/fragments/RunningMateSelectFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/RunningTimeFragment.kt
  app/src/main/res/layout/activity_create_challenge.xml
  app/src/main/res/layout/activity_myrun2.xml
  app/src/main/res/layout/fragment_create_crew1.xml
  app/src/main/res/layout/fragment_create_solo1.xml
  app/src/main/res/layout/fragment_myrun.xml
Labels: :sparkles:루나:sparkles:, :exclamation:REFRACTOR

#85 #71 챌린지목록&디테일 화면 api 연동
  .idea/deploymentTargetSelector.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/model/data/BaseResponse.kt
  app/src/main/java/com/example/yourun/model/data/CrewChallengeDetailRes.kt
  app/src/main/java/com/example/yourun/model/data/CrewChallengeResponse.kt
  app/src/main/java/com/example/yourun/model/data/PersonalChallengeResponse.kt
  app/src/main/java/com/example/yourun/model/data/SoloChallengeDetailRes.kt
  app/src/main/java/com/example/yourun/model/data/Tendency.kt
  app/src/main/java/com/example/yourun/model/data/response/ChallengeItem.kt
  app/src/main/java/com/example/yourun/model/data/response/MemberTendencyInfo.kt
  app/src/main/java/com/example/yourun/model/network/ApiService.kt
  app/src/main/java/com/example/yourun/model/repository/ChallengeRepository.kt
  app/src/main/java/com/example/yourun/model/repository/MateRepository.kt
  app/src/main/java/com/example/yourun/view/activities/ChallengeDetailActivity.kt
  app/src/main/java/com/example/yourun/view/activities/ChallengeDetailTeamActivity.kt
  app/src/main/java/com/example/yourun/view/activities/ChallengeListActivity.kt
  app/src/main/java/com/example/yourun/view/activities/CrewChallengeDetailActivity.kt
  app/src/main/java/com/example/yourun/view/activities/MainActivity.kt
  app/src/main/java/com/example/yourun/view/activities/SoloChallengeDetailActivity.kt
  app/src/main/java/com/example/yourun/view/adapters/ChallengeAdapter.kt
  app/src/main/java/com/example/yourun/view/adapters/MateRankingAdapter.kt
  app/src/main/java/com/example/yourun/view/fragments/ChallengeListFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/CrewChallengeFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/HomeFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/SoloChallengeFragment.kt
  app/src/main/java/com/example/yourun/viewmodel/ChallengeViewModel.kt
  app/src/main/java/com/example/yourun/viewmodel/ChallengeViewModelFactory.kt
  app/src/main/java/com/example/yourun/viewmodel/CrewChallengeDetailViewModel.kt
  app/src/main/java/com/example/yourun/viewmodel/SoloChallengeDetailViewModel.kt
  app/src/main/res/drawable/bg_user_hashtag.xml
  app/src/main/res/drawable/btn_crew_default.xml
  app/src/main/res/drawable/btn_crew_selected.xml
  app/src/main/res/drawable/btn_floating_plus.xml
  app/src/main/res/drawable/btn_personal_default.xml
  app/src/main/res/drawable/btn_personal_selected.xml
  app/src/main/res/drawable/img_crew_badge_count_1.xml
  app/src/main/res/drawable/img_crew_badge_count_2.xml
  app/src/main/res/drawable/img_crew_badge_count_3.xml
  app/src/main/res/drawable/img_personal_badge_count_1.xml
  app/src/main/res/drawable/img_personal_badge_count_2.xml
  app/src/main/res/drawable/img_personal_badge_count_3.xml
  app/src/main/res/layout/activity_crew_challenge_detail.xml
  app/src/main/res/layout/activity_solo_challenge_detail.xml
  app/src/main/res/layout/fragment_challenge_list.xml
  app/src/main/res/layout/fragment_create_crew1.xml
  app/src/main/res/layout/fragment_crew_challenge.xml
  app/src/main/res/layout/fragment_personal_challenge.xml
  app/src/main/res/layout/item_crew_challenge.xml
  app/src/main/res/layout/item_solo_challenge.xml
  gradle/libs.versions.toml
Labels: :sparkles:아리:sparkles:, :white_check_mark:FEATURE, :computer:UI

#97 refactor/화면연결 완료
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/view/activities/CreateSoloActivity.kt
  app/src/main/java/com/example/yourun/view/fragments/CreateCrew2Fragment.kt
  app/src/main/java/com/example/yourun/view/fragments/CreateSolo2Fragment.kt
  app/src/main/java/com/example/yourun/view/fragments/MyRunFragment.kt
Labels: :sparkles:루나:sparkles:, :exclamation:REFRACTOR

#98 fix : 오류 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/yourun/view/activities/ChallengeStartActivity.kt
  app/src/main/java/com/example/yourun/view/activities/CrewChallengeStartActivity.kt
  app/src/main/java/com/example/yourun/view/activities/ResultCrewActivity.kt
  app/src/main/java/com/example/yourun/view/fragments/HomeFragment.kt
  app/src/main/res/drawable/bgd_popup_background_crew.xml
  app/src/main/res/drawable/bgd_popup_background_solo.xml
  app/src/main/res/drawable/ic_badge_crew.png
  app/src/main/res/drawable/ic_badge_solo.png
  app/src/main/res/layout/activity_running_crew_challenge.xml
  app/src/main/res/layout/dialog_reward_crew.xml
  app/src/main/res/layout/dialog_reward_solo.xml
Labels: :sparkles:졍:sparkles:, :hammer:FIX

#110 fix : 온보딩 오류 수정
  app/src/main/java/com/example/yourun/view/fragments/AppExpFragment2.kt
  app/src/main/java/com/example/yourun/view/fragments/HomeFragment.kt
  app/src/main/java/com/example/yourun/view/fragments/ResultFragment.kt
  app/src/main/res/layout/fragment_app_exp2.xml
  app/src/main/res/layout/fragment_app_exp3.xml
  app/src/main/res/layout/fragment_app_exp4.xml
  app/src/main/res/layout/fragment_app_exp5.xml
  app/src/main/res/layout/fragment_app_exp6.xml
Labels: :sparkles:졍:sparkles:, :hammer:FIX
